version: '3'

tasks:
  build:
    desc: "Build the Go project"
    cmds:
      - go build -o bin/ ./...

  release:
    desc: "Build, compress, and create checksums for the Go project release"
    cmds:
      - for:
          matrix:
            OS: ["windows", "linux", "darwin"]
            ARCH: ["amd64", "arm64"]
        cmd: |
          mkdir -p release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}/faraday; \
          cp config.yaml.example release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}/faraday/config.yaml; \
          if [ "{{ .ITEM.OS }}" = "windows" ]; then \
            GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} go build -ldflags "-s -w" -o release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}/fai.exe ./...; \
            zip -r release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.zip release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}; \
            sha256sum release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.zip > release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.zip.sha256; \
            sha256sum release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.zip >> release/checksums.txt; \
            rm -r release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}; \
          else \
            GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} go build -ldflags "-s -w" -o release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}/fai ./...; \
            tar -czf release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.tar.gz -C release fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}; \
            sha256sum release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.tar.gz > release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.tar.gz.sha256; \
            sha256sum release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}.tar.gz >> release/checksums.txt; \
            rm -r release/fai-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}; \
          fi
    silent: false
