name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install go-task
      run: |
        TASK_VERSION=$(curl --silent "https://api.github.com/repos/go-task/task/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        curl -L "https://github.com/go-task/task/releases/download/${TASK_VERSION}/task_linux_amd64.tar.gz" -o task.tar.gz
        tar -xzf task.tar.gz -C /usr/local/bin task
        rm task.tar.gz

    - name: Build release binaries
      run: task release

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      id: bump_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        name: Release v${{ steps.bump_version.outputs.new_tag }}
        draft: false
        prerelease: false
        files: |
          release/fai-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}