name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build
      run: |
        mkdir -p build/${{ matrix.goos }}-${{ matrix.goarch }}
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.goos }}-${{ matrix.goarch }}/myapp

  bump_version:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP_LEVEL: patch
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

  release:
    runs-on: ubuntu-latest
    needs: [build, bump_version]
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.bump_version.outputs.new_tag }}
        name: Release v${{ needs.bump_version.outputs.new_tag }}
        draft: false
        prerelease: false
        files: |
          build/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}